{{- if .Values.appa.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demo.serviceAccountName" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
  {{- with .Values.appa.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
