apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}-appa
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.appa.service.type }}
  ports:
    - port: {{ .Values.appa.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: app-a
