# cat ~/.docker/config.json
# kubectl create secret generic regcred \
#    --from-file=.dockerconfigjson=<path/to/.docker/config.json> \
#    --type=kubernetes.io/dockerconfigjson

apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-auth
  namespace: default
data:
  .dockerconfigjson: 
type: kubernetes.io/dockerconfigjson