apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
  labels:
    app: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      imagePullSecrets:
        - name: dockerhub-auth
      containers:
        - name: app-a
          image: boroserik/private:app-av2
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_NAME
              value: "k8s"
          ports:
            - containerPort: 8080