apiVersion: v1
kind: Service
metadata:
  name: encoder
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.encoder.service.type }}
  ports:
    - port: {{ .Values.encoder.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: encoder
